apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: carlosedp/alertmanager
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 1
  serviceAccountName: alertmanager-main
  version: v0.14.0
